name: Validación de ejecución

on:
  pull_request:
    branches: [ "qa" ]

jobs:
  dockerize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Construir imagen de docker
        run: |
          docker build -t buscaminas-cpp .

      - name: Si ocurre un error, falla el workflow
        run: exit 1
        if: failure()
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Dar permisos de ejecucion
        run: |
          chmod +x runtime.sh

      - name: Ejecuta script de prueba
        run: |
          ./runtime.sh